# Generated by Django 2.2.3 on 2019-07-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_cout',
            field=models.IntegerField(default=0),
        ),
    ]
